### ISSUE TITLE
bart: memory aliasing issue in Union

### ISSUE THREAD

**Issue by maisem** [gaissmai/bart#16]
`(*Table).Union` seems to result in shard memory between the receiving and other `(*Table)`.

This results in unexpected side effects especially incases where some tables are computed once and then reused for the lifetime of the process. These tables end up getting mutated when unioned with other shorter lived tables.

I would have expected to not have any memory aliasing between the (*Table) apart from the values being shallow copied as described in the docs which doesn't matter for my use case as I am using `Table[struct{}]`

**Comment by gaissmai** [comment]
@maisem you are just right, thanks a lot!

**Comment by gaissmai** [comment]
merged and releases as v0.4.1
