### ISSUE TITLE
When subnetwork is deleted from table lookup/get still reports individual IPs as present

### ISSUE THREAD

**Issue by s3rj1k** [gaissmai/bart#21]
When subnetwork is deleted from table lookup/get still reports individual IPs as present.

Maybe I misunderstand how to use this module correctly, below is an example test:

```
package main

import (
	"net/netip"
	"testing"

	"github.com/gaissmai/bart"
	"github.com/stretchr/testify/assert"
)

func mustParsePrefix(s string) netip.Prefix {
	pfx, err := netip.ParsePrefix(s)
	if err != nil {
		panic(err)
	}

	return pfx
}

func mustParseAddr(s string) netip.Addr {
	addr, err := netip.ParseAddr(s)
	if err != nil {
		panic(err)
	}

	return addr
}

func TestBART(t *testing.T) {
	var ok bool

	tbl := new(bart.Table[struct{}])

	{
		// 192.168.40.1 - 192.168.43.254
		tbl.Insert(mustParsePrefix("192.168.42.1/22"), struct{}{})

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.40.1"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.43.254"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.42.242"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("10.0.42.42"))
		assert.False(t, ok)
	}

	{
		tbl.Delete(mustParsePrefix("192.168.42.42/32"))

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.40.1"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.43.254"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.42.42"))
		assert.False(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("10.0.42.42"))
		assert.False(t, ok)
	}

	{
		// 192.168.42.1 - 192.168.42.254
		tbl.Delete(mustParsePrefix("192.168.42.1/24"))

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.40.1"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.43.254"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.42.242"))
		assert.False(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("10.0.42.42"))
		assert.False(t, ok)
	}
}
```

**Comment by gaissmai** [comment]
You can only delete prefixes that you have inserted **exactly**, otherwise Delete() is a noop.

bart is a routing table and not an IPset where you can cut out parts of a prefix with delete and the rest remains.

If you are looking for something like this you have to use either `github.com/go4org/netipx ` or `github.com/gaissmai/iprange`.

Your test should look like:

```golang
package main

import (
	"net/netip"
	"testing"

	"github.com/gaissmai/bart"
	"github.com/stretchr/testify/assert"
)

var mustParsePrefix netip.MustParsePrefix 
var mustParseAddr netip.MustParseAddr

func TestBART(t *testing.T) {
	var ok bool

	tbl := new(bart.Table[struct{}])

	{
		// 192.168.40.0 - 192.168.43.255
		tbl.Insert(mustParsePrefix("192.168.40.0/22"), struct{}{})

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.40.0"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.43.255"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.42.242"))
		assert.True(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("10.0.42.42"))
		assert.False(t, ok)
	}

	{
		tbl.Delete(mustParsePrefix("192.168.40.0/22"))

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.40.0"))
		assert.False(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.43.255"))
		assert.False(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("192.168.42.42"))
		assert.False(t, ok)

		_, _, ok = tbl.Lookup(mustParseAddr("10.0.42.42"))
		assert.False(t, ok)
	}
}

```

**Comment by s3rj1k** [comment]
@gaissmai Thanks for referencing external modules.

Do you maybe have an idea, performace-wise, `github.com/go4org/netipx` / `github.com/gaissmai/iprange` vs `bart` where deletion is done via Insert-Mark approach, how this would scale?

(`Insert-Mark approach` - instead of deleting none inserted key, just insert that key with some value that marks this record as deleted)

**Comment by gaissmai** [comment]
what is your use case?

**Comment by s3rj1k** [comment]
> what is your use case?

fast lookup and low resources footprint for IPset like behavior (+ adding whole networks, so hash table not applicable)

**Comment by gaissmai** [comment]
You can't delete subnetworks in a routing table, because several prefixes could be affected, no routing table that I know of covers such a use case.

It is still not clear to me what exactly you really want to do.

**Comment by s3rj1k** [comment]
> It is still not clear to me what exactly you really want to do.

Ideally some sort of VLSM, but can settle to hacking around with values as mentioned before, maybe if you consider your module used not as routing table but as a general IPSet that would help.

**Comment by gaissmai** [comment]
I'm sorry, you'll have to do that yourself, it's outside of what `bart` is written for.

I hereby close this issue

**Comment by s3rj1k** [comment]
> I'm sorry, you'll have to do that yourself, it's outside of what `bart` is written for.

I was not asking you to do it :), just asking what do you think about performance in regards to `iprange` vs `bart` with tagging instead of deletion

**Comment by gaissmai** [comment]
A routing algorithm is not suitable for such a use case, try `netipx` or `iprange` and make comparative benchmarks.

**Comment by gaissmai** [comment]
one more remark: use `github.com/gaissmai/iprange` for IPset operations together with `github.com/gaissmai/interval `for lookups, it's naturally not as fast as a CIDR based routing table algorithm but maybe fast enough for your use case.

Or use `github.com/gaissmai/iprange` for IPset operations and transform it into pure CIDRs and use `bart` for CIDR lookups, it depends on the use case and how dynamic you have to be.

**Comment by s3rj1k** [comment]
Will play with suggested combinations, thanks

**Comment by gaissmai** [comment]
@s3rj1k hi again, could you provide a real world problem of your use case?

Sure, you could insert a (sub)-prefix and mark it invalid in the **payload**, then you would get a match with longest-prefix-match and you have to check the payload for additional info, but this is totally up to you.

Yes this should be very fast in comparison to `netipx` and/or `iprange`.

But again, please send me your real world problem.

**Comment by s3rj1k** [comment]
> could you provide a real world problem of your use case?

As mentioned above just an abstraction of IPset for Firewall application where the actual set can change dynamically (multiple sources), that blacklists networks but can also whitelist some parts of it (by single IP or range or whatever is possible) but it has to be reasonably fast for lookups and not use huge amount of memory.

(consideration here is that whitelist is significantly smaller than flattened blacklist)

**Comment by gaissmai** [comment]
You just have to note that `get/lookup` always searches for the **lpm**, i.e. always the smallest range in the routing table that contains the IP you are looking for, regardless of what payload you use to mark the prefix, whether black or white.

**Comment by s3rj1k** [comment]
> You just have to note that `get/lookup` always searches for the **lpm**, i.e. always the smallest range in the routing table that contains the IP you are looking for, regardless of what payload you use to mark the prefix, whether black or white.

so best is to whitelist per ip(v4)/32 ? and just ignore ranges and subnets

**Comment by gaissmai** [comment]
it belongs to your use case ;)

**Comment by gaissmai** [comment]
@s3rj1k If I understand your problem correctly, then I think it would be better to work with two independent routing tables, a whitelist table and a blacklist table.

**Comment by s3rj1k** [comment]
> @s3rj1k If I understand your problem correctly, then I think it would be better to work with two independent routing tables, a whitelist table and a blacklist table.

One of the options yes, thought about it after your initial comment about `inserted exactly`.

It will be even possible to use some hashmap for whitelist case if there is no need to support networks.
