### ISSUE TITLE
how to get prefix by ip?

### ISSUE THREAD

**Issue by farwydi** [gaissmai/bart#59]
Hello 
You recently removed the prefix return value from the lookup function.

How can I now get the prefix from the IP?

old:
```go
Lookup(ip netip.Addr) (lpm netip.Prefix, val V, ok bool)
```

new:
```go
Lookup(ip netip.Addr) (val V, ok bool)
```

I see only this option
```go
bart.Table[netip.Prefix]
```

**Comment by tobez** [comment]
I would imagine

```go
(lpm, val, ok) := t.LookupPrefixLPM(netip.PrefixFrom(ip, ip.BitLen())
```

should do the trick, no?

EDIT: take the fact that ip.Prefix returns two values into account.
EDIT2: just use PrefixFrom()

**Comment by gaissmai** [comment]
use LookupPrefixLPM and read the docstring

> If LookupPrefixLPM is to be used for IP addresses, they must be converted to /32 or /128 prefixes.

**Comment by gaissmai** [comment]
what is your use case? The fastest method is to add the prefix to the payload and unwrap it from the returned value.

I added LookupLPM in the devel branch, but building the lpm out of the trie is expensive (20-30% slower than Lookup)

**Comment by gaissmai** [comment]
no feedback, closing the issue
